on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push 
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      env:
        CI: false
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: mangalorecart.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: public_html/sdemo/
